### ISSUE TITLE
【親】共有機能実装

### ISSUE THREAD

**Issue by waka320** [jphacks/ng_2406#20]
- [ ] （フロント）UI作成 #21 
- [ ] （フロント）URLから、必要なパラメータをバックに渡し、帰ってきたデータを表示 #22 
- [ ] （バック）フロントから来た暗号化されたパラメータを復号、データをフロントに返す #23 
- [ ] （バック）出力ごとに固有のIDを作成、それを暗号化にしてフロント用のURLにする #24
